api_homepage:
    path:     /
    defaults: { _controller: KDSMAPIBundle:Default:index }

users:
    path:     /users
    defaults: { _controller: KDSMAPIBundle:Users:index }

users:
     path:     /users/view
     defaults: { _controller: KDSMAPIBundle:Users:view }

