parameters:
    api.url: 'http://wonderwall.ox.nfq.lt/kickertable/api/v1/events'
    api.user: 'nfq'
    api.password: 'labas'
    api.csv_filepath: '/uploads/failas.csv'
    api.xml_filepath: '/uploads/xml_writer_output.xml'
    api.csv_iterator_delimiter: ','
    api.csv_iterator_keys: ['id', 'timeSec', 'usec', 'type', 'data']

services:
    api.api_caller:
        class: KDSM\APIBundle\Services\Caller
        arguments:
            [%api.url%, %api.user%, %api.password%]
    api.api_db_manager:
        class: KDSM\APIBundle\Services\DbManager
        arguments:
            entityManager: @doctrine.orm.entity_manager
    api.api_csv_iterator:
        class: KDSM\APIBundle\Services\fileIO\CsvIterator
        arguments: [%kernel.root_dir%, %api.csv_filepath%, %api.csv_iterator_delimiter%, %api.csv_iterator_keys%]
    api.api_manager:
        class: KDSM\APIBundle\Services\fileIO\Manager
        calls:
            - [setCaller, [@api.api_caller]]
