# src/KDSM/ContentBundle/Resources/config/doctrine/User.orm.yml
KDSM\ContentBundle\Entity\User:
    type:  entity
    repositoryClass: KDSM\ContentBundle\Entity\UserRepository
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        cardId:
            column: card_id
            type: integer
            nullable: TRUE
        profilePicturePath:
            column: profile_picture_path
            type: string
            length: '255'
            nullable: TRUE
        skillLevel:
            column: skill_level
            type: integer
            nullable: TRUE
        lastPlayed:
            column: last_played
            type: datetime
            nullable: TRUE
        wins:
            column: wins
            type: integer
            nullable: TRUE
        losses:
            column: losses
            type: integer
            nullable: TRUE
        lookingForGame:
            column: looking_for_game
            type: boolean
            nullable: TRUE
    oneToMany:
        usersQueues:
          targetEntity: UsersQueues
          mappedBy: user
          cascade: [ persist ]
