kdsm_content:
    resource: "@KDSMContentBundle/Resources/config/routing.yml"
    prefix:   /
api:
    resource: "@KDSMAPIBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


