KDSM\APIBundle\Entity\TableEvent:
    type: entity
    table: table_event
    repositoryClass: KDSM\APIBundle\Entity\TableEventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        eventId:
            column: event_id
            type: integer
        timesec:
            type: datetime
        usec:
            type: string
            length: '10'
        type:
            type: string
            length: '20'
        data:
            type: string
            length: 255
    lifecycleCallbacks: {  }
