<?php

namespace APIBundle\Entity;

use Doctrine\Common\EventManager;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\Entity;

/**
 * TableEventTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableEventTypeRepository extends EntityRepository
{
//    public function __construct(EntityManager $em, )
    public function findByEventName($name){

    }

}
