<?php

namespace APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TableEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableEventRepository extends EntityRepository
{
    public function getLatestEvent(){
        $query = $this->createQueryBuilder('tb');
        return $query->select('MAX(tb.eventId)')->getQuery()->getResult()[0][1];
    }
}
