<?php

namespace APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TableEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableEventRepository extends EntityRepository
{
}
