admin:
    path:     /admin
    defaults: { _controller: KDSMContentBundle:Admin:index }

admin_changeparameter:
    path: /adminChangeParameter
    defaults: { _controller: KDSMContentBundle:Admin:change }

admin_removeparameter:
    path: /adminRemoveParameter
    defaults: {_controller: KDSMContentBundle:Admin:remove}

kdsm_content_homepage:
    path:     /
    defaults: { _controller: KDSMContentBundle:Default:index }

logout:
    path:     /logout
    defaults: { _controller: KDSMContentBundle:Users:logout }

user_view:
    path:     /users/view/{id}
    defaults: { _controller: KDSMContentBundle:Users:view }

queue:
    path:     /queue
    defaults: { _controller: KDSMContentBundle:Queue:index }

statistics:
    path:     /statistics
    defaults: { _controller: KDSMContentBundle:Statistics:index }

kdsm_live_game:
    path:     /content/live_game
    defaults: { _controller: KDSMContentBundle:Default:liveGame }

kdsm_queue:
    path:     /queue/{method}/{queueId}
    defaults: { _controller: KDSMContentBundle:Queue:queue, queueId: null}

kdsm_queue_user_join_request:
    path:     /queue/user_invite/{users}-{queue}
    defaults: { _controller: KDSMContentBundle:Queue:sendUserQueueJoinRequest }

kdsm_queue_user_join_decline:
    path:     /queue/user_decline/{queue}
    defaults: { _controller: KDSMContentBundle:Queue:userQueueJoinDecline }

get_notifications:
    path:     /content/notifications
    defaults: { _controller: KDSMContentBundle:Default:getNotifications }

view_notification:
    path: /content/viewnotification
    defaults: {_controller: KDSMContentBundle:Default:viewNotification }