kdsm_content_homepage:
    path:     /hello/{name}
    defaults: { _controller: KDSMContentBundle:Default:index }

users:
    path:     /users
    defaults: { _controller: KDSMContentBundle:Users:index }

users_register:
    path:     /register
    defaults: { _controller: KDSMContentBundle:Users:register }

user_login:
    path:     /login
    defaults: { _controller: KDSMContentBundle:Users:login }

user_view:
    path:     /users/view/{id}
    defaults: { _controller: KDSMContentBundle:Users:view }