kdsm_content_homepage:
    path:     /homepage
    defaults: { _controller: KDSMContentBundle:Default:index }

logged_homepage:
    path:     /
    defaults: { _controller: KDSMContentBundle:Default:loggedHomepage }

logout:
        path:     /logout
        defaults: { _controller: KDSMContentBundle:Users:logout }

users_register:
    path:     /register
    defaults: { _controller: KDSMContentBundle:Users:register }

user_login:
    path:     /login
    defaults: { _controller: KDSMContentBundle:Users:login }

user_view:
    path:     /users/view/{id}
    defaults: { _controller: KDSMContentBundle:Users:view }

queue:
    path:     /queue
    defaults: { _controller: KDSMContentBundle:Queue:index }
