parameters:
    table.busy_threshold: 10
    table.check_period: 60
services:
    kdsm_content.cache_manager:
        class: KDSM\ContentBundle\Services\Redis\CacheManager
        arguments: [@snc_redis.default, @doctrine.orm.entity_manager]
    kdsm_content.table_busy_check:
        class: KDSM\ContentBundle\Services\Statistics\BusyCheck
        arguments: [@doctrine.orm.entity_manager, %table.busy_threshold%, %table.check_period%]
    kdsm_content.live_score:
        class: KDSM\ContentBundle\Entity\LiveScore
    kdsm_content.live_score_manager:
        class: KDSM\ContentBundle\Services\LiveScore\LiveScoreManager
        arguments: [@kdsm_content.live_score, @kdsm_content.table_busy_check, @doctrine.orm.entity_manager, @kdsm_content.cache_manager]
    kdsm_content.queue_manager:
        class: KDSM\ContentBundle\Services\QueueManager
        arguments: [@doctrine.orm.entity_manager]
    kdsm_content.parameter_getter:
        class: KDSM\ContentBundle\Services\ParameterService
        arguments: [@doctrine.orm.entity_manager]
    kdsm_content.registration.form.type:
        class: KDSM\ContentBundle\Form\Type\RegistrationFormType
        tags:
           - { name: form.type, alias: kdsm_content_registration }
    kdsm_content.listener.notification:
        class: KDSM\ContentBundle\EventListener\KDSMNotificationListener
        tags:
           - { name: kdsm_content.notification_listener, event: kdsm_content.notification_create, method: onNotificationCreate }
        arguments: [@doctrine.orm.entity_manager]
