parameters:
    table.busy_threshold: 10
services:
    kdsm_content.table_busy_check:
        class: KDSM\ContentBundle\Services\Statistics\BusyCheck
        arguments: [@doctrine.orm.entity_manager, %table.busy_threshold%]
