parameters:
    table.busy_threshold: 1
    table.check_period: 60
services:
    kdsm_content.cache_manager:
        class: KDSM\ContentBundle\Services\Redis\CacheManager
        arguments: [@snc_redis.default, @doctrine.orm.entity_manager]
    kdsm_content.table_busy_check:
        class: KDSM\ContentBundle\Services\Statistics\BusyCheck
        arguments: [@doctrine.orm.entity_manager]
        calls:
          - [setTableBusyThreshold, [%table.busy_threshold%]]
          - [setTableCheckPeriod, [%table.check_period%]]
    kdsm_content.live_score_manager:
        class: KDSM\ContentBundle\Services\LiveScore\LiveScoreManager
        arguments: [@doctrine.orm.entity_manager]
        calls:
          - [setTableBusyCheck, [@kdsm_content.table_busy_check]]
          - [setCacheManager, [@kdsm_content.cache_manager]]
          - [setQueueManager, [@kdsm_content.queue_manager]]
    kdsm_content.queue_manager:
        class: KDSM\ContentBundle\Services\QueueManager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]
    kdsm_content.parameter_getter:
        class: KDSM\ContentBundle\Services\ParameterService
        arguments: [@doctrine.orm.entity_manager]
    kdsm_content.statistics_updater:
        class: KDSM\ContentBundle\Services\Statistics\StatisticsService
        arguments: [@doctrine.orm.entity_manager]
    kdsm_content.registration.form.type:
        class: KDSM\ContentBundle\Form\Type\RegistrationFormType
        tags:
           - { name: form.type, alias: kdsm_content_registration }
    kdsm_content.listener.notification:
        class: KDSM\ContentBundle\EventListener\KDSMNotificationListener
        tags:
           - { name: kernel.event_listener, event: kdsm_content.notification_create, method: onNotificationCreate }
        arguments: [@doctrine.orm.entity_manager]
