parameters:
    api.url: 'http://wonderwall.ox.nfq.lt/kickertable/api/v1/events'
    api.user: 'nfq'
    api.password: 'labas'

services:
    api.api_caller:
        class: APIBundle\Services\APICaller
        arguments:
            - [%api.url%]
            - [%api.user%]
            - [%api.password%]
    api.api_xml_writer:
        class: APIBundle\Services\APIXmlWriter
        arguments: ['%kernel.root_dir%']
    api.api_csv_writer:
            class: APIBundle\Services\APICsvWriter
            arguments: ['%kernel.root_dir%']
    api.api_manager:
            class: APIBundle\Services\APIManager
            calls:
                - [setCaller, ['@api.api_caller']]
                - [setParser, ['@api.api_xml_writer']]
