parameters:
    apibundle.db.table_prefix: api_
    api.url: 'http://wonderwall.ox.nfq.lt/kickertable/api/v1/events'
    api.user: 'nfq'
    api.password: 'labas'
    api.csv_filepath: '/uploads/csv_writer_output.csv'
    api.xml_filepath: '/uploads/xml_writer_output.xml'
    api.csv_iterator_delimiter: ','
    api.csv_iterator_keys: ['id', 'timesec', 'usec', 'type', 'data']

services:
    mybundle.tblprefix_subscriber:
        class: APIBundle\Subscriber\TablePrefixSubscriber
        arguments: [%apibundle.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
    api.api_caller:
        class: APIBundle\Services\Caller
        arguments:
            [%api.url%, %api.user%, %api.password%]
#    api.api_xml_writer:
#        class: APIBundle\Services\APIXmlWriter
#        arguments: [%kernel.root_dir%, %api.xml_filepath%]
#    api.api_csv_writer:
#        class: APIBundle\Services\APICsvWriter
#        arguments: [%kernel.root_dir%, %api.csv_filepath%]
    api.api_csv_iterator:
        class: APIBundle\Services\CsvIterator
        arguments: [%kernel.root_dir%, %api.csv_filepath%, %api.csv_iterator_delimiter%, %api.csv_iterator_keys%]
    api.api_manager:
        class: APIBundle\Services\Manager
        calls:
            - [setCaller, [@api.api_caller]]
#            - [setParser, [@api.api_xml_writer]]
