homepage:
    path:     /
    defaults: { _controller: KDSMFirstPagesBundle:Home:index }

reservationpage:
    path:     /reservation
    defaults: { _controller: KDSMFirstPagesBundle:Reservation:index }

profilepage:
    path:     /profile
    defaults: { _controller: KDSMFirstPagesBundle:Profile:index }