defaultpage:
    path:     /default
    defaults: { _controller: KDSMFirstPagesBundle:Default:index }

homepage:
    path:     /
    defaults: { _controller: KDSMFirstPagesBundle:Home:index }

reservationpage:
    path:     /reservation
    defaults: { _controller: KDSMFirstPagesBundle:Reservation:index }
