<?php

namespace KDSM\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueueRepository extends EntityRepository
{
    public function persistObject($newQueue)
    {
        $this->getEntityManager()->persist($newQueue);
        $this->getEntityManager()->flush();
        $this->getEntityManager()->clear();
    }

}
