<?php

namespace KDSM\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticRepository extends EntityRepository
{
    public function addStatistic($statistic_id, $stats){
        $stat = new Statistic();
        $stat->setStatisticId($statistic_id);
        $stat->setStats($stats);

        $em = $this->getEntityManager();
        $em->persist($stat);
        $em->flush();
    }

}
